# Multiple Linear Regression
**Amacımız, birden fazla değişkenden oluşan durumlar için nasıl çözüm uygulayabiliriz. Mesela bir kişinin boy ve kilosuna göre yaş tahmini yapmak için.**
**Diyelim elimizde 20 tane özellik var. Bunlardan hangilerini alabiliriz, hangileri arasında bağlantı kurabiliriz vb. sorulara çözüm bulmak isteyebiliriz.**

In [122]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

**Formül = $b0 + b1*x1 + b2*x2 + ..... + bn*xn $** 

**b0 = sabit sayı**


**x'lerin hepsi 1. dereceden denklemler**

**Basit Lineer Regresyon = satışlar = a + b(ay)** 


Aya Göre Satış


**Çoklu Lineer Regresyon = Boy = a + b(yaş) + c(kilo) + d(ayakkabı numarası)** 


Yaş, kilo ayakkabı numarasına göre boy tahmini

**Bu verilerin hepsinin elimizde olduğu kabul edilir.**

# Dummy Variable(Kukla Değişken)
**Bir değişkeni ifade eden başka değişken diyebiliriz. Örneğin cinsiyet kategorik bir veriydi. Ancak biz OHE yapıp onu numerik veri haline getirdik. Bu kolon kukla değişken olur**

**Ancak bu işlem her zaman iyi sonuç vermez. Bazı makine öğrenmesi algoritmaları bu işleme dirençliyken bazı makine öğrenmesi algoritmaları dirençli değildir. Mesela bir kolon için 100 farklı kolon eklediğimizde, önceden varolan eski kolonlar işlevini yitirmeye başlar çünkü algoritma kendini bu yeni eklenen 100 kolona doğru çeker.**

**Dummy Variable oluşturduktan sonra mutlaka yeni oluşturulan kolonlarla bu kolonların oluşturulduğu kolon aynı anda alınmamalıdır. Mesela Kadın olup olmaması kolonunu almaya karar verdiysek cinsiyet ve erkek kolonunu atmamız gerek!! Sadece erkek ve kadını aldık diyelim. Bu kolonlar birbirine bağlıdır(biri 0ken diğeri 1) dolayısıyla bu 2 kolon sistemi etkileyebilir! Bu tuzaktır. Bu tuzağı atlamamız lazım(birbirine eklenince de biribirinden çıkartılınca da 1 değerini verir)**

**Önemli olan kolonlar arasında bağlantı olmamasını sağlamak ama bazı zamanlarda olabilir. Öyle durumlarda dummy variablelarda da kendi içerisinde seçim yapılması gerekir.**

**Ancak mesela İstanbul-Ankara-İzmir olarak 3 farklı kolon var. Bir kişinin istanbullu olmaması demek diğer 2 şehirden birinden olması anlamına geldiği için bu durumlarda 3 kolonu da almamız gerek!!!**

# P Value(Probility Value)

**h0(sıfır hipotezi) = başlangıçta ortaya atılan hipotez olarak geçer. "Her kutuda 100 tane kurabiye vardır."**

**h1(ters hipotez) = Başlangıçta verdiğimiz hipotezin tersi. Hipotezi ne zaman çürütebiliriz? 1 tane hatalı değer(outlier) bu hipotezi çürütemeyebilir.**

**P value = Kaç tane aksi örnek bulursam bu hipotezi çürütebilirim? bunun cevabını verir.**

**p value = genelde %5 alınır. p değeri %5'in altındaysa h0'ın hatalı olma ihtimali artar. Dolayısıyla h1'in doğru olma değeri artar.(h0 ve h1 birbirinin tersi.**

# Değişken Seçimi

**Birden fazla değişken olduğunda acaba her değişken, bağımlı değişkeni aynı oranda mı etkiliyor? hatta bazı değişkenler hiç etkilemiyor bile olabilir. Bazı değişkenler sisteme olumsuz etki de yapabilir.**

### 1-) Bütün Değişkenleri Dahil Etmek: 
**Elimizdeki tüm değişkenleri dahil edip hiçbirini elememek. Bazı durumlarda bu yöntemi kullanmak zorunda kalabiliriz(sistemi olumsuz etkilese bile). Mesela hali hazırda bulunan bir sistemin başarısını ölçmek gibi(özellikleri önceden seçilmiş) veya Keşif için denenebilir(diğer yöntemleri kullanmadan bir ön fikir elde etmek için)**

### 2-) Geriye Doğru Eleme(Backward Elimination):
**Çok kullanılan bir yöntemdir. Önce bütün değişkenler dahil edilir, sonra teker teker elenerek ilerlenir. 
En yüksek p-value değerine sahip olan değişken ele alınır. P>0.05 ise bir sonraki adıma geçilir, değilse makine öğrenmesi sonlandırılır.
Daha sonra, en yüksek değere sahip p-value sistemden kaldırılır ve yeni değişen seçilir. Yeniden p>0.05 olup olmadığına bakılır... Böyle devam eder.**

### 3-) İleriye Doğru Eleme(Forward Selection):
**Yeniden döngü ile yapılır(2. sinde olduğu gibi) En düşük değere sahip olan p-value değişkeni alınır. 
P<0.05 sağlandığı sürece yeni değişken eklenmeye devam edilir. Ne zaman ki p<0.05 olursa makine öğrenimi sonlanır.**

### 4-) Çift Yönlü Eleme(Bidirectional Elemination)
**2 ve 3'ün birleşimi. Amacımız hem ileri hem geri ilerlemek. Bazı durumlarda birden fazla Significant level(0.05) belirlenebilir: Biri ileriye giderken, biri geri giderken.
Yine en düşük p-value değeri ele alınır. Bu değişken sabit tutularak diğer tüm değişkenler sisteme dahil edilir. 
SL değişkeninin altında kalan değişkenler sistemde kalır, eski değişkenlerden hiçbiri sistemden çıkarılmaz.**

### 5-) Skor Karşılaştırması(Score Comparison):
**P-value, Sl falan belirlemeyip  tüm kuralları kendimiz koyarız. Bir başarı kriteri belirleyeceğiz. Olası regresyon yöntemleri inşa edilir. Belirlenen kriter sağlanana kadar inşa devam eder.**

In [129]:
data = pd.read_csv("veriler.csv")
data

   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

In [130]:
#cinsiyet ve ülke kolonlarını numerik değere çevireceğiz.
ulke=data.iloc[:,0:1].values
le = preprocessing.LabelEncoder()
ulke[:,0] = le.fit_transform(data.iloc[:,0])

ohe = preprocessing.OneHotEncoder()
ulke = ohe.fit_transform(ulke).toarray()

cinsiyet = data.iloc[:, -1:]
ohe = preprocessing.OneHotEncoder()
cinsiyet = ohe.fit_transform(cinsiyet).toarray()

In [131]:
#Şimdi dataframeleri birleştiriyoruz
df = pd.DataFrame(data=ulke, index=range(22), columns=['fr', 'tr', 'usa'])

Yas = data.iloc[:, 1:4]
df1 = pd.DataFrame(data=Yas, index=range(22), columns=['boy', 'kilo', 'yas'])

#ancak cinsiyet alırken dummy variablelara dikkat ediyoruz. Ondan sadece tek kolonu alacağız. Sadece erkek kolonunu aldık!
#cinsiyet = 1 ise erkek, 0 ise kız
df3 = pd.DataFrame(data=cinsiyet[:, 0:1], index=range(22), columns=['cinsiyet'])

sonuc1df = pd.concat([df, df1], axis=1)

sonuc3df = pd.concat([sonuc1df, df3], axis=1)#Cinsiyet One-Hot Endocing'i için bir df
sonuc3df

     fr   tr  usa  boy  kilo  yas  cinsiyet
0   0.0  1.0  0.0  130    30   10       1.0
1   0.0  1.0  0.0  125    36   11       1.0
2   0.0  1.0  0.0  135    34   10       0.0
3   0.0  1.0  0.0  133    30    9       0.0
4   0.0  1.0  0.0  129    38   12       1.0
5   0.0  1.0  0.0  180    90   30       1.0
6   0.0  1.0  0.0  190    80   25       1.0
7   0.0  1.0  0.0  175    90   35       1.0
8   0.0  1.0  0.0  177    60   22       0.0
9   0.0  0.0  1.0  185   105   33       1.0
10  0.0  0.0  1.0  165    55   27       0.0
11  0.0  0.0  1.0  155    50   44       0.0
12  0.0  0.0  1.0  160    58   39       0.0
13  0.0  0.0  1.0  162    59   41       0.0
14  0.0  0.0  1.0  167    62   55       0.0
15  1.0  0.0  0.0  174    70   47       1.0
16  1.0  0.0  0.0  193    90   23       1.0
17  1.0  0.0  0.0  187    80   27       1.0
18  1.0  0.0  0.0  183    88   28       1.0
19  1.0  0.0  0.0  159    40   29       0.0
20  1.0  0.0  0.0  164    66   32       0.0
21  1.0  0.0  0.0  166    56   42       0.0

In [132]:
#yeniden train ve test bloklarımızı oluşturuyoruz.
#bağımlı değişken cinsiyet kolonu
x_train, x_test, y_train, y_test = train_test_split(sonuc1df, df3, test_size=0.33, random_state=0)

print(x_train)
print("\n\n", y_train)
print("\n\n",x_test)
print("\n\n",y_test)

     fr   tr  usa  boy  kilo  yas
8   0.0  1.0  0.0  177    60   22
6   0.0  1.0  0.0  190    80   25
16  1.0  0.0  0.0  193    90   23
4   0.0  1.0  0.0  129    38   12
2   0.0  1.0  0.0  135    34   10
5   0.0  1.0  0.0  180    90   30
17  1.0  0.0  0.0  187    80   27
9   0.0  0.0  1.0  185   105   33
7   0.0  1.0  0.0  175    90   35
18  1.0  0.0  0.0  183    88   28
3   0.0  1.0  0.0  133    30    9
0   0.0  1.0  0.0  130    30   10
15  1.0  0.0  0.0  174    70   47
12  0.0  0.0  1.0  160    58   39


     cinsiyet
8        0.0
6        1.0
16       1.0
4        1.0
2        0.0
5        1.0
17       1.0
9        1.0
7        1.0
18       1.0
3        0.0
0        1.0
15       1.0
12       0.0


      fr   tr  usa  boy  kilo  yas
20  1.0  0.0  0.0  164    66   32
10  0.0  0.0  1.0  165    55   27
14  0.0  0.0  1.0  167    62   55
13  0.0  0.0  1.0  162    59   41
1   0.0  1.0  0.0  125    36   11
21  1.0  0.0  0.0  166    56   42
11  0.0  0.0  1.0  155    50   44
19  1.0  0.0  0.0  159    40   29


     cinsiyet
20       0.0
10       0.0
14       0.0
13       0.0
1        1.0
21       0.0
11       0.0
19       0.0

In [133]:
#Şimdi ise Multiple Linear Regression işlemlerine geçiyoruz.
lr = LinearRegression()
lr.fit(x_train, y_train)#6 boyutlu bir veri kullanılacak

LinearRegression()

In [134]:
#tahmin işlemine geçelim
#görüldüğü gibi 8 örnekte 2 hata var(kalanını doğru kabul edelim)
y_predict = lr.predict(x_test)
print(y_predict)
print(y_test)

[[ 0.98720204]
 [-0.12036863]
 [ 0.05009703]
 [ 0.07137418]
 [ 0.72473935]
 [ 0.64615044]
 [-0.03567453]
 [ 0.32612171]]
    cinsiyet
20       0.0
10       0.0
14       0.0
13       0.0
1        1.0
21       0.0
11       0.0
19       0.0

In [135]:
#Şimdi ise diğer değerlere göre boyu tahmin etmeye çalışacağız. Yani boy harici x, boy y değeri olacak
#boy'u ayri bir değer olarak aldık. Boyun solunda ve sağında kalan değişkenleri aldık ve yeni bir df olarak birleştirdik
boy = sonuc3df.iloc[:, 3:4]
sol = sonuc3df.iloc[:, :3]
sag = sonuc3df.iloc[:, 4:]

newdf = pd.concat([sol, sag], axis=1)
newdf

     fr   tr  usa  kilo  yas  cinsiyet
0   0.0  1.0  0.0    30   10       1.0
1   0.0  1.0  0.0    36   11       1.0
2   0.0  1.0  0.0    34   10       0.0
3   0.0  1.0  0.0    30    9       0.0
4   0.0  1.0  0.0    38   12       1.0
5   0.0  1.0  0.0    90   30       1.0
6   0.0  1.0  0.0    80   25       1.0
7   0.0  1.0  0.0    90   35       1.0
8   0.0  1.0  0.0    60   22       0.0
9   0.0  0.0  1.0   105   33       1.0
10  0.0  0.0  1.0    55   27       0.0
11  0.0  0.0  1.0    50   44       0.0
12  0.0  0.0  1.0    58   39       0.0
13  0.0  0.0  1.0    59   41       0.0
14  0.0  0.0  1.0    62   55       0.0
15  1.0  0.0  0.0    70   47       1.0
16  1.0  0.0  0.0    90   23       1.0
17  1.0  0.0  0.0    80   27       1.0
18  1.0  0.0  0.0    88   28       1.0
19  1.0  0.0  0.0    40   29       0.0
20  1.0  0.0  0.0    66   32       0.0
21  1.0  0.0  0.0    56   42       0.0

In [136]:
#yeniden train ve test kümeleri oluşturuyoruz

xtrain, xtest, ytrain, ytest = train_test_split(newdf, boy, test_size=0.33, random_state=0)
print(xtrain)
print("\n\n", ytrain)
print("\n\n",xtest)
print("\n\n",ytest)

     fr   tr  usa  kilo  yas  cinsiyet
8   0.0  1.0  0.0    60   22       0.0
6   0.0  1.0  0.0    80   25       1.0
16  1.0  0.0  0.0    90   23       1.0
4   0.0  1.0  0.0    38   12       1.0
2   0.0  1.0  0.0    34   10       0.0
5   0.0  1.0  0.0    90   30       1.0
17  1.0  0.0  0.0    80   27       1.0
9   0.0  0.0  1.0   105   33       1.0
7   0.0  1.0  0.0    90   35       1.0
18  1.0  0.0  0.0    88   28       1.0
3   0.0  1.0  0.0    30    9       0.0
0   0.0  1.0  0.0    30   10       1.0
15  1.0  0.0  0.0    70   47       1.0
12  0.0  0.0  1.0    58   39       0.0


     boy
8   177
6   190
16  193
4   129
2   135
5   180
17  187
9   185
7   175
18  183
3   133
0   130
15  174
12  160


      fr   tr  usa  kilo  yas  cinsiyet
20  1.0  0.0  0.0    66   32       0.0
10  0.0  0.0  1.0    55   27       0.0
14  0.0  0.0  1.0    62   55       0.0
13  0.0  0.0  1.0    59   41       0.0
1   0.0  1.0  0.0    36   11       1.0
21  1.0  0.0  0.0    56   42       0.0
11  0.0  0.0  1.0    50   44       0.0
19  1.0  0.0  0.0    40   29       0.0


     boy
20  164
10  165
14  167
13  162
1   125
21  166
11  155
19  159

In [137]:
#şimdi yeniden lineer öğretme yapıyoruz
lr.fit(xtrain, ytrain)
y_boy_predict = lr.predict(xtest)
print(y_boy_predict)
print(ytest)

[[182.26638686]
 [152.87161474]
 [162.79386375]
 [158.30668577]
 [130.82888952]
 [173.96138408]
 [150.12782663]
 [157.26898922]]
    boy
20  164
10  165
14  167
13  162
1   125
21  166
11  155
19  159

**Önceki örneklerde tüm kolonları kullandık. Acaba doğru mu yapıyoruz?**


**Backward Elimination Yöntemi**


**Öncelikle bu değişkenlerin hangisi sisteme daha fazla etki ediyor? onu görmek için bir dizi oluşturup o değişkenleri o diziye koyacağız**

**Formüle bakarsak: $𝑏0+𝑏1∗𝑥1+𝑏2∗𝑥2+.....+𝑏𝑛∗𝑥𝑛$ burada b0 değeri var(sabit değer) ancak biz burada kalan tüm değerleri eklerken o b0 değerine sahip değiliz. Öncelikle o b0 değerini bulmamız gerek**

In [143]:
#amacımız sabit değere katsayı olarak 1 eklemek. Burada yaptığımız şey, bizim dataframemize bir sütun ekliyoruz
#O sütundaki tüm değerler 1'e eşit!
X = np.append(arr = np.ones((22, 1)).astype(int), values=newdf, axis=1)

#Şimdi ise tüm kolonları alıyoruz. Böyle almamızın sebebi: eleme yöntemi yapacağımız için bazı kolonları çıkartacağız.
#Başta tamamını alıp p-values hesaplayacağız
xl = newdf.iloc[:, [0, 1, 2, 3, 4, 5]].values
xl = np.array(xl, dtype=float)
#Burada yaptığımız şey: 6 tane kolonun tek tek boy üzerindeki etkisini ölçmek(1'in boy üzerindeki etkisi, 2'nin boy üzerindeki etkisi vb.)
#Buna göre modelin ne kadar başarılı olduğunu buluruz.
model = sm.OLS(boy, xl).fit()#istatistiksel değerlerimizi çıkartmaya yarıyor.
print(model.summary())#bir rapor şeklinde çıktı verir.
#bizim için önemli olanlar p değeri(ne kadar düşükse o kadar iyi)
#şu an bizim için sorunlu olan x5'i elememiz gerek çünkü en yüksek p değeri onda

                            OLS Regression Results
==============================================================================
Dep. Variable:                    boy   R-squared:                       0.885
Model:                            OLS   Adj. R-squared:                  0.849
Method:                 Least Squares   F-statistic:                     24.69
Date:                Sun, 15 Nov 2020   Prob (F-statistic):           5.41e-07
Time:                        00:00:10   Log-Likelihood:                -73.950
No. Observations:                  22   AIC:                             159.9
Df Residuals:                      16   BIC:                             166.4
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           114.0688      8.145     14.005      0.000      96.802     131.335
x2           108.3030      5.736     18.880      0.000      96.143     120.463
x3           104.4714      9.195     11.361      0.000      84.978     123.964
x4             0.9211      0.119      7.737      0.000       0.669       1.174
x5             0.0814      0.221      0.369      0.717      -0.386       0.549
x6           -10.5980      5.052     -2.098      0.052     -21.308       0.112
==============================================================================
Omnibus:                        1.031   Durbin-Watson:                   2.759
Prob(Omnibus):                  0.597   Jarque-Bera (JB):                0.624
Skew:                           0.407   Prob(JB):                        0.732
Kurtosis:                       2.863   Cond. No.                         524.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [144]:
#şimdi x5'i attık ve tekrar bir model oluşturduk
xl = newdf.iloc[:, [0, 1, 2, 3, 5]].values
xl = np.array(xl, dtype=float)
model = sm.OLS(boy, xl).fit()
print(model.summary())f

#Burada gördüğümüz en yüksek değer 0.031 ama kabul edilebilir bir değer. Ama rahatsızım diyorsak çıkarabiliriz.
#Daha küçük bir SL elde etmek istersek**

                            OLS Regression Results
==============================================================================
Dep. Variable:                    boy   R-squared:                       0.884
Model:                            OLS   Adj. R-squared:                  0.857
Method:                 Least Squares   F-statistic:                     32.47
Date:                Sun, 15 Nov 2020   Prob (F-statistic):           9.32e-08
Time:                        00:04:15   Log-Likelihood:                -74.043
No. Observations:                  22   AIC:                             158.1
Df Residuals:                      17   BIC:                             163.5
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           115.6583      6.734     17.175      0.000     101.451     129.866
x2           109.0786      5.200     20.978      0.000      98.108     120.049
x3           106.5445      7.090     15.026      0.000      91.585     121.504
x4             0.9405      0.104      9.029      0.000       0.721       1.160
x5           -11.1093      4.733     -2.347      0.031     -21.096      -1.123
==============================================================================
Omnibus:                        0.871   Durbin-Watson:                   2.719
Prob(Omnibus):                  0.647   Jarque-Bera (JB):                0.459
Skew:                           0.351   Prob(JB):                        0.795
Kurtosis:                       2.910   Cond. No.                         397.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [145]:
#x5'i eliyoruz
xl = newdf.iloc[:, [0, 1, 2, 3]].values
xl = np.array(xl, dtype=float)
model = sm.OLS(boy, xl).fit()
print(model.summary())

#Şimdi görüldüğü gibi tüm p-values'lar 0 oldu

                            OLS Regression Results
==============================================================================
Dep. Variable:                    boy   R-squared:                       0.847
Model:                            OLS   Adj. R-squared:                  0.821
Method:                 Least Squares   F-statistic:                     33.16
Date:                Sun, 15 Nov 2020   Prob (F-statistic):           1.52e-07
Time:                        00:06:04   Log-Likelihood:                -77.131
No. Observations:                  22   AIC:                             162.3
Df Residuals:                      18   BIC:                             166.6
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           119.8136      7.265     16.491      0.000     104.550     135.077
x2           109.8084      5.804     18.919      0.000      97.615     122.002
x3           114.4212      6.984     16.382      0.000      99.747     129.095
x4             0.7904      0.092      8.595      0.000       0.597       0.984
==============================================================================
Omnibus:                        2.925   Durbin-Watson:                   2.855
Prob(Omnibus):                  0.232   Jarque-Bera (JB):                1.499
Skew:                           0.605   Prob(JB):                        0.473
Kurtosis:                       3.416   Cond. No.                         369.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [149]:
#O zaman Backward Yöntemi ile eleme yaptık. Elimizde olan son veriler ile ilgili bir regresyon modeli oluşturalım
after_backwarddf = pd.DataFrame(data=xl, index=range(22), columns=['fr', 'tr', 'usa', 'kilo'])
x_train, x_test, y_train, y_test = train_test_split(after_backwarddf, boy, test_size=0.33, random_state=0)

print(x_train)
print("\n\n", y_train)
print("\n\n",x_test)
print("\n\n",y_test)

     fr   tr  usa   kilo
8   0.0  1.0  0.0   60.0
6   0.0  1.0  0.0   80.0
16  1.0  0.0  0.0   90.0
4   0.0  1.0  0.0   38.0
2   0.0  1.0  0.0   34.0
5   0.0  1.0  0.0   90.0
17  1.0  0.0  0.0   80.0
9   0.0  0.0  1.0  105.0
7   0.0  1.0  0.0   90.0
18  1.0  0.0  0.0   88.0
3   0.0  1.0  0.0   30.0
0   0.0  1.0  0.0   30.0
15  1.0  0.0  0.0   70.0
12  0.0  0.0  1.0   58.0


     boy
8   177
6   190
16  193
4   129
2   135
5   180
17  187
9   185
7   175
18  183
3   133
0   130
15  174
12  160


      fr   tr  usa  kilo
20  1.0  0.0  0.0  66.0
10  0.0  0.0  1.0  55.0
14  0.0  0.0  1.0  62.0
13  0.0  0.0  1.0  59.0
1   0.0  1.0  0.0  36.0
21  1.0  0.0  0.0  56.0
11  0.0  0.0  1.0  50.0
19  1.0  0.0  0.0  40.0


     boy
20  164
10  165
14  167
13  162
1   125
21  166
11  155
19  159

In [150]:
lr.fit(x_train, y_train)
y_predictlast = lr.predict(x_test)
print(y_test)
print(y_predictlast)

    boy
20  164
10  165
14  167
13  162
1   125
21  166
11  155
19  159
[[170.90273989]
 [150.39360044]
 [156.23302674]
 [153.73041546]
 [139.02382298]
 [162.56070232]
 [146.22258165]
 [149.2134422 ]]